# Generated by Django 4.1.5 on 2023-01-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='state',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_item',
            name='promo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
