# Generated by Django 4.1.5 on 2023-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shipping_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
